// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PromptsController from "./prompts_controller"
application.register("prompts", PromptsController)
